### ISSUE TITLE
Runtime Error: Import Error: No module named parse

### ISSUE THREAD

**Issue by mikejr83** [sebastientaggart/docker-cloudmapper#2]
Running the code I'm getting this:

```
Traceback (most recent call last):,
  File "cloudmapper.py", line 69, in <module>,
    main(),
  File "cloudmapper.py", line 53, in main,
    module = importlib.import_module(full_package_name),
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module,
    __import__(name),
  File "/opt/cloudmapper/commands/audit.py", line 6, in <module>,
    import urllib.parse,
ImportError: No module named parse
```

I'm not sure if this is an issue with the underlying cloudmapper source or an artifact from running in a container.

**Comment by ggriffin** [comment]
I'm seeing the same:
`ImportError: No module named parse`

**Comment by jangle83** [comment]
Also having this problem.

**Comment by mikejr83** [comment]
The build pulls from master. Can anyone get the latest in cloudmapper working not in a container?

**Comment by jessert** [comment]
I found changing all references to python to python3 in entrypoint.sh resolves the issue.  Also had to add additional pip packages to the Dockerfile
RUN pip install pyjq netaddr policyuniverse boto3
